title: "OffsecAR"
description: "أخبار Offensive Security يومياً بالعربي · OffsecAR"
url: "https://malekalthubiany.github.io"
baseurl: "/OffsecAR"
lang: ar
direction: rtl

author:
  name: "OffsecAR"
  twitter: "@OffsecARE"

permalink: /:year/:month/:day/:title/

collections:
  blogs:
    output: true
    permalink: /blogs/:name/

defaults:
  - scope:
      path: ""
      type: "blogs"
    values:
      layout: "blog"

plugins:
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
